services:
    _defaults:
        autowire: true
        autoconfigure: true

    Backend2Plus\UploadBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UploadBundle.php'

    Backend2Plus\UploadBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Backend2Plus\UploadBundle\Service\UploadService:
        arguments:
            $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'
            $privateUploadsFilesystem: '@oneup_flysystem.private_uploads_filesystem_filesystem'

    # Alias for backward compatibility
    App\Bundles\Upload\MultipleUploadBundleService: '@Backend2Plus\UploadBundle\Service\MultipleUploadBundleService'

      # Backend2Plus\UploadBundle\Controller\UploadController:
      #     arguments:
      #         $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem'
      #         $privateUploadsFilesystem: '@oneup_flysystem.private_uploads_filesystem'
