services:
    _defaults:
        autowire: true
        autoconfigure: true

    Backend2Plus\UploadBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UploadBundle.php'
    

    Backend2Plus\UploadBundle\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    Backend2Plus\UploadBundle\Service\UploadService:
        arguments:
            $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem_filesystem'
            $privateUploadsFilesystem: '@oneup_flysystem.private_uploads_filesystem_filesystem'
            $maxWidth: '%upload_bundle.image_resize.max_width%'
            $maxHeight: '%upload_bundle.image_resize.max_height%'
            $quality: '%upload_bundle.image_resize.quality%'

      # Backend2Plus\UploadBundle\Controller\UploadController:
      #     arguments:
      #         $publicUploadsFilesystem: '@oneup_flysystem.public_uploads_filesystem'
      #         $privateUploadsFilesystem: '@oneup_flysystem.private_uploads_filesystem'
